version: 2

project_name: remote-console
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - id: remote-console
    main: ./cmd/remote-console
    binary: remote-console
    goos:
      - linux
    goarch:
      - amd64
      # TODO We want ARM builds, but need ARM base images and conman packages for this.
      #- arm64
    goamd64:
      - v3
    env:
      - CGO_ENABLED=1
      - >-
        {{- if eq .Os "linux" }}
          {{- if eq .Arch "arm64"}}CC=aarch64-linux-gnu-gcc{{- end }}
        {{- end }}

    ldflags:
      - "-s -w -X main.GitCommit={{.Commit}} \
         -X main.BuildTime={{.Timestamp}} \
         -X main.Version={{.Version}} \
         -X main.GitBranch={{.Branch}} \
         -X main.GitTag={{.Tag}} \
         -X main.GitState={{ .Env.GIT_STATE }} \
         -X main.BuildHost={{ .Env.BUILD_HOST }} \
         -X main.GoVersion={{ .Env.GO_VERSION }} \
         -X main.BuildUser={{ .Env.BUILD_USER }} "

dockers_v2:
  - id: remote-console
    ids:
      - remote-console
    dockerfile: Dockerfile
    images:
      - ghcr.io/openchami/{{.ProjectName}}
    tags:
      - "{{ .Tag }}"
      - "{{ .Major }}"
      - "{{ .Major }}.{{ .Minor }}"
      - "latest"
    platforms:
      - linux/amd64
      # TODO: Add linux/arm64 when ARM base images and conman packages are available
    flags:
      - "--pull"
      - "--target=ubuntu-goreleaser"
    annotations:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
    extra_files:
      - LICENSE
      - CHANGELOG.md
      - README.md
      - configs/
      - scripts/

archives:
  - formats: ["tar.gz"]
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - LICENSE
      - CHANGELOG.md
      - README.md

checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'


# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
