#
# MIT License
#
# (C) Copyright 2021-2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#

networks:
  host:

services:
  condat-postgres:
    hostname: console-data-cray-console-data-postgres
    image: docker.io/postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=console
      - POSTGRES_USER=console
      - POSTGRES_DB=console
    networks:
      - host
    healthcheck:
      test: ["CMD", "psql", "-U", "console"]
      interval: 5s
      timeout: 5s
      retries: 5
  cray-console-data:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=condat-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=console
      - POSTGRES_USER=console
      - POSTGRES_PASSWD=console
    hostname: cray-console-data
    depends_on:
      condat-postgres:
        condition: service_healthy
    networks:
      - host
