// Code generated by Fabrica dev. DO NOT EDIT.
// Template: cmd/fabrica/generate.go:generateVersionedRegistrationCode
// Generated: 2026-07-13T14:10:55Z
//
// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

package resources

import (
	"fmt"

	v1 "github.com/OpenCHAMI/remote-console/apis/remote-console.openchami.io/v1"
	"github.com/openchami/fabrica/pkg/codegen"
)

// RegisterAllResources registers all discovered resources with the generator.
// This file is auto-generated. Re-run 'fabrica generate' after adding resources.
func RegisterAllResources(gen *codegen.Generator) error {
	if err := gen.RegisterResource(&v1.Console{}); err != nil {
		return fmt.Errorf("failed to register Console: %w", err)
	}
	gen.ConfigureResource("Console", codegen.ResourceConfig{
		URLPath:    "/remote-console/consoles",
		Operations: codegen.ResourceOperationsFromNames([]string{"list"}),
	})

	return nil
}
