#!/usr/bin/expect --

# Copyright 2020-2021, 2024 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# (MIT License)

# This can be called from within the context of conman to
# establish an ssh connection to a Mountain node console.
# Usage and examples below assume this script's name is
# ssh-console and located on the system under /usr/bin
#
# Usage: ssh-console xname
#  Example: ssh-console x5000c3s6b0n0
#
# Example /etc/conman.conf entry:
# console name="x5000c3s6b0n0" dev="/usr/bin/ssh-console x5000c3s6b0n0"
#

set env(TERM) xterm
set controller [string range [lindex $argv 0] 0 end-2]
set session [string range [lindex $argv 0] end-1 end]
set timeout -1
set pid [spawn ssh -o ServerAliveInterval=180 -o ServerAliveCountMax=5 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i /var/log/console/conman.key $session@$controller]
exit -onexit {
  exec kill $pid
  wait $pid
  exp_exit
}
interact


# to get this to work we need to do something along the lines of the
# other passworded logins -- there are a number of scripts in there to
# get the screen session, but since we're logging in as root we'll
# either need to change user and then do the `screen -x` or figure out
# the right script to call to get us into the console in a single
# command, but it's not clear if we can do that easily
