//
//  MIT License
//
//  (C) Copyright 2020-2022, 2024 Hewlett Packard Enterprise Development LP
//
//  Permission is hereby granted, free of charge, to any person obtaining a
//  copy of this software and associated documentation files (the "Software"),
//  to deal in the Software without restriction, including without limitation
//  the rights to use, copy, modify, merge, publish, distribute, sublicense,
//  and/or sell copies of the Software, and to permit persons to whom the
//  Software is furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included
//  in all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
//  THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
//  OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
//  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
//  OTHER DEALINGS IN THE SOFTWARE.
//

// This file contains the functions to configure and retrieve credentials

package console

import (
	"bytes"
	"crypto/sha256"
	"log"
	"os"
	"time"

	compcreds "github.com/Cray-HPE/hms-compcredentials"
	sstorage "github.com/Cray-HPE/hms-securestorage"
)

// Location of the Mountain BMC console ssh key pair files.
// These are obtained or generated by console-operator.
const sshConsoleKeyPath string = "/var/log/console/conman.key"
const sshConsoleKeyPubCertPath string = "/var/log/console/conman.key-cert.pub"

// Look up the creds for the input endpoints with retries
func getPasswordsWithRetries(bmcXNames []string, maxTries, waitSecs int) map[string]compcreds.CompCredentials {
	// NOTE: in update config thread

	var passwords map[string]compcreds.CompCredentials = nil
	for numTries := 0; numTries < maxTries; numTries++ {
		log.Printf("Get passwords with retry: %d", numTries)
		// get passwords from vault
		passwords = getPasswords(bmcXNames)

		// make sure we have something for all entries
		foundAll := true
		for _, nn := range bmcXNames {
			_, ok := passwords[nn]
			if !ok {
				log.Printf("Missing credentials for %s", nn)
				foundAll = false
			}
		}

		// if we got all the passwords we are done
		if foundAll {
			log.Printf("Retrieved all passwords")
			return passwords
		}

		// if we did not get all passwords try again until maxAttempts
		log.Printf("Attempt %d - Only retrieved %d of %d River creds from vault, waiting and trying again...",
			numTries, len(passwords), len(bmcXNames))
		time.Sleep(time.Duration(waitSecs) * time.Second)
	}

	// We have reached max attempts, bail with what we have
	log.Printf("Maximum password attempts reached, configuring conman with what we have.")
	return passwords
}

// Look up the creds for the input endpoints
func getPasswords(bmcXNames []string) map[string]compcreds.CompCredentials {
	// NOTE: in update config thread

	// if running in debug mode, skip hsm query
	if DebugOnly {
		log.Print("DEBUGONLY mode - skipping creds query")
		return nil
	}

	// Get the passwords from Hashicorp Vault
	log.Print("Gathering creds from vault")

	// Create the Vault adapter and connect to Vault
	ss, err := sstorage.NewVaultAdapter("secret")
	if err != nil {
		log.Panicf("Error: %#v\n", err)
	}

	// Initialize the CompCredStore struct with the Vault adapter.
	ccs := compcreds.NewCompCredStore("hms-creds", ss)

	// Read the credentials for a list of components from the CompCredStore
	// (backed by Vault).
	ccreds, err := ccs.GetCompCreds(bmcXNames)
	if err != nil {
		log.Panicf("Error: %#v\n", err)
	}

	return ccreds
}

var previousPrivateKeyHash []byte = nil
var previousPublicCertHash []byte = nil

// function to hash a string
func hashString(s string) ([]byte, error) {
	hasher := sha256.New()
	if _, err := hasher.Write([]byte(s)); err != nil {
		return nil, err
	}
	return hasher.Sum(nil), nil
}

// Ensure that node console key files are present.
func ensureConsoleKeysPresent() bool {
	retVal := false

	// if running in debug mode there won't be any nodes or vault present
	if DebugOnly {
		log.Print("Running in debug mode - skipping mountain cred generation")
		return retVal
	}

	// Get the key from secure storage

	// Get the base path
	vaultBasePath := os.Getenv("VAULT_BASE_PATH")
	if len(vaultBasePath) == 0 {
		log.Printf("Error: VAULT_BASE_PATH environment variable is not set, defaulting to 'secret'")
		vaultBasePath = "secret"
	}

	// Get the vault role
	vaultRole := os.Getenv("VAULT_ROLE")
	if len(vaultRole) == 0 {
		log.Printf("Error: VAULT_ROLE environment variable is not set, defaulting to ''")
		vaultRole = ""
	}

	// Get the private key name
	consolePrivateKeyName := os.Getenv("CONSOLE_PRIVATE_KEY_NAME")
	if len(consolePrivateKeyName) == 0 {
		log.Printf("Error: CONSOLE_PRIVATE_KEY_NAME environment variable is not set, defaulting to 'bmc-console-key'")
		consolePrivateKeyName = "bmc-console-key"
	}

	// TODO: For now we using vault, but this should be configurable
	ss, err := sstorage.NewVaultAdapterAs(vaultBasePath, vaultRole)
	if err != nil {
		log.Panicf("Error: Unable to create secure storage adapter: %#v\n", err)
	}

	// Get the key
	var consolePrivateKey string
	err = ss.Lookup(consolePrivateKeyName, &consolePrivateKey)
	if err != nil {
		log.Panicf("Error: Unable to lookup private key: %#v\n", err)
	}

	// See if this is a new key
	newHash, err := hashString(consolePrivateKey)
	if err != nil {
		log.Printf("Error: Failed to hash the private ssh key received from Vault. Err: %s", err)
	} else if previousPrivateKeyHash == nil || !(bytes.Equal(newHash, previousPrivateKeyHash)) {
		// This is a new key
		retVal = true
		previousPrivateKeyHash = newHash

		// Write the private key to the local file system.
		err = os.WriteFile(sshConsoleKeyPath, []byte(consolePrivateKey), 0600)
		if err != nil {
			log.Printf("Error: Failed to write our the private ssh key received from Vault. Err: %s", err)
			return retVal
		}
		log.Printf("Console ssh key file created")
		return retVal
	} else {
		// This is the same key as before, no need to write it again
		log.Printf("Console ssh key file already exists")
		return retVal
	}

	// Now get the cert if we have it
	var consolePublicCert string
	err = ss.Lookup(consolePrivateKeyName+"-cert", &consolePublicCert)
	if err != nil {
		log.Printf("Warning: Unable to lookup public cert key: %#v\n", err)
		return retVal
	}

	// See if this is a new cert
	newHash, err = hashString(consolePublicCert)
	if err != nil {
		log.Printf("Error: Failed to hash the public ssh cert received from Vault. Err: %s", err)
	} else if previousPublicCertHash == nil || !(bytes.Equal(newHash, previousPublicCertHash)) {
		// This is a new cert
		retVal = true
		previousPublicCertHash = newHash

		// Write the public cert to the local file system.
		err = os.WriteFile(sshConsoleKeyPubCertPath, []byte(consolePublicCert), 0644)
		if err != nil {
			log.Printf("Error: Failed to write our the public ssh cert received from Vault. Err: %s", err)
			return retVal
		}
		log.Printf("Console ssh cert file created")
		return retVal
	} else {
		// This is the same cert as before, no need to write it again
		log.Printf("Console ssh cert file already exists")
		return retVal
	}

	return retVal
}
