// Code generated by Fabrica dev. DO NOT EDIT.
// Template: server/handlers.go.tmpl
// Generated: 2026-07-13T14:14:06Z
//
// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API handlers for Console resources.
//
// To modify this code:
//   1. Edit the template file: pkg/codegen/templates/handlers.go.tmpl
//   2. Run 'fabrica generate' to regenerate
//   3. Do NOT edit this file directly - changes will be lost
//
// Generated handlers provide:
//   - GET /remote-console/consoles (list all consoles)
//
// Authorization: Add custom middleware for authentication/authorization

// Version Support: Available (see version context in handlers)
//
// To enable full version conversion for this resource:
//  1. Add new version: fabrica add version <group> <version>
//  2. Implement converter: apis/<group>/<version>/converter.go
//  3. Add version-aware storage: GetConsoleResourceWithVersion()
//  4. Register versions in cmd/server/main.go
package main

import (
	"fmt"

	"net/http"
)

// GetConsoles returns all Console resources
func GetConsoles(w http.ResponseWriter, r *http.Request) {
	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	consoles, err := ListConsoleResources(r.Context())
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to load consoles: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, consoles)
}
