// Fabrica scaffold generated by Fabrica dev and customized for remote-console.
// Future `fabrica generate` runs update *_generated.go files, not this file.
//
// SPDX-FileCopyrightText: Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	_ "github.com/OpenCHAMI/remote-console/pkg/apiversion"
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	"github.com/openchami/fabrica/pkg/versioning"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

// Config holds all configuration for the service
type Config struct {
	// Server Configuration
	Port         int    `mapstructure:"port"`
	Host         string `mapstructure:"host"`
	ReadTimeout  int    `mapstructure:"read_timeout"`
	WriteTimeout int    `mapstructure:"write_timeout"`
	IdleTimeout  int    `mapstructure:"idle_timeout"`

	// Feature Flags

	AuthEnabled bool `mapstructure:"auth_enabled"`
	Debug       bool `mapstructure:"debug"`
}

// DefaultConfig returns the default configuration
func DefaultConfig() *Config {
	return &Config{
		Port:         26776,
		Host:         "0.0.0.0",
		ReadTimeout:  15,
		WriteTimeout: 15,
		IdleTimeout:  60,

		AuthEnabled: true,
		Debug:       false,
	}
}

var (
	cfgFile string
	config  *Config
)

func main() {
	if err := rootCmd.Execute(); err != nil {
		log.Fatal(err)
	}
}

var rootCmd = &cobra.Command{
	Use:   "remote-console",
	Short: "OpenCHAMI remote console service",
	Long:  `remote-console - A Fabrica-generated OpenCHAMI service`,
	RunE:  runServer,
}

var serveCmd = &cobra.Command{
	Use:   "serve",
	Short: "Start the remote-console server",
	Long:  `Start the remote-console HTTP server with the configured options`,
	RunE:  runServer,
}

func init() {
	cobra.OnInitialize(initConfig)

	// Global flags
	rootCmd.PersistentFlags().StringVar(&cfgFile, "config", "", "config file (default is $HOME/.remote-console.yaml)")
	rootCmd.PersistentFlags().Bool("debug", false, "Enable debug logging")

	// Server flags
	serveCmd.Flags().IntP("port", "p", 26776, "Port to listen on")
	serveCmd.Flags().String("host", "0.0.0.0", "Host to bind to")
	serveCmd.Flags().Int("read-timeout", 15, "Read timeout in seconds")
	serveCmd.Flags().Int("write-timeout", 15, "Write timeout in seconds")
	serveCmd.Flags().Int("idle-timeout", 60, "Idle timeout in seconds")

	serveCmd.Flags().Bool("auth-enabled", true, "Enable authentication")

	// Bind flags to viper
	cobra.CheckErr(viper.BindPFlags(serveCmd.Flags()))
	cobra.CheckErr(viper.BindPFlags(rootCmd.PersistentFlags()))
	cobra.CheckErr(viper.BindPFlag("read_timeout", serveCmd.Flags().Lookup("read-timeout")))
	cobra.CheckErr(viper.BindPFlag("write_timeout", serveCmd.Flags().Lookup("write-timeout")))
	cobra.CheckErr(viper.BindPFlag("idle_timeout", serveCmd.Flags().Lookup("idle-timeout")))
	cobra.CheckErr(viper.BindPFlag("auth_enabled", serveCmd.Flags().Lookup("auth-enabled")))

	// Add subcommands
	rootCmd.AddCommand(serveCmd)

	rootCmd.AddCommand(versionCmd)

	// Generated by Fabrica v0.4.0+: export and import commands (Ent storage only)

}

func initConfig() {
	config = DefaultConfig()

	if cfgFile != "" {
		viper.SetConfigFile(cfgFile)
	} else {
		// Search for config in home directory
		home, err := os.UserHomeDir()
		cobra.CheckErr(err)

		viper.AddConfigPath(home)
		viper.AddConfigPath(".")
		viper.SetConfigType("yaml")
		viper.SetConfigName(".remote-console")
	}

	// Environment variables
	viper.SetEnvPrefix("REMOTE_CONSOLE")
	viper.SetEnvKeyReplacer(strings.NewReplacer("-", "_", ".", "_"))
	viper.AutomaticEnv()

	// Read config file if it exists
	if err := viper.ReadInConfig(); err == nil {
		log.Printf("Using config file: %s", viper.ConfigFileUsed())
	}

	// Unmarshal config
	if err := viper.Unmarshal(config); err != nil {
		log.Fatalf("Unable to decode into config struct: %v", err)
	}

	// Set debug logging
	if config.Debug {
		log.SetFlags(log.LstdFlags | log.Lshortfile)
		log.Println("Debug logging enabled")
	}
}

func runServer(cmd *cobra.Command, args []string) error {
	log.Printf("Starting remote-console server...")

	storageCleanup, err := initializeStorage(config)
	if err != nil {
		return err
	}
	defer storageCleanup()

	runtimeCleanup, err := initializeEventingAndReconciliation(config)
	if err != nil {
		return err
	}
	defer runtimeCleanup()

	// Register resource prefixes for UID generation
	// This is required before any handlers can create resources
	if err := registerResourcePrefixes(); err != nil {
		return fmt.Errorf("failed to register resource prefixes: %w", err)
	}

	remoteConfig := DefaultRemoteConsoleConfig()
	if os.Getenv("RCS_HTTP_LISTEN") == "" {
		remoteConfig.HttpListen = fmt.Sprintf("%s:%d", config.Host, config.Port)
	}
	if err := applyRemoteConsoleEnv(&remoteConfig); err != nil {
		return err
	}

	serviceCtx, serviceStop := context.WithCancel(context.Background())
	defer serviceStop()

	if err := startRemoteConsoleRuntime(serviceCtx, remoteConfig); err != nil {
		return err
	}
	initializeConsoleWebSocketHandler(remoteConfig)

	// Setup router
	r := chi.NewRouter()

	// Add middleware
	r.Use(middleware.Logger)
	r.Use(middleware.Recoverer)
	r.Use(middleware.RequestID)
	r.Use(middleware.RealIP)
	r.Use(middleware.RedirectSlashes)

	// Version negotiation (Accept header `version=` or URL strategy)
	// Initialize and use global version registry when versioning is enabled.
	// Note: VersionNegotiationMiddleware currently uses versioning.VersionRegistry
	// Versioning support will be fully wired in a future update.
	r.Use(versioning.VersionNegotiationMiddleware(versioning.GlobalVersionRegistry, nil))

	authnMiddleware, authzMiddleware, err := initializeAuthMiddleware(config)
	if err != nil {
		return err
	}
	var consoleWebSocketEndpoint http.Handler = http.HandlerFunc(serveConsoleWebSocket)
	if config.AuthEnabled {
		consoleWebSocketEndpoint = authnMiddleware(consoleWebSocketEndpoint)
		if authzMiddleware != nil {
			consoleWebSocketEndpoint = authzMiddleware(consoleWebSocketEndpoint)
		}
	}
	r.Use(consoleWebSocketMiddleware(consoleWebSocketEndpoint))

	if config.Debug {
		r.Mount("/debug", middleware.Profiler())
	}

	// Public endpoints (bypass AuthN/AuthZ)
	r.Group(func(public chi.Router) {
		// Service health (always public)
		public.Get("/health", healthHandler)
		public.Get("/openapi.json", ServeOpenAPISpec)
		public.Get("/docs", ServeSwaggerUI)
		if config.AuthEnabled {
			// Allow CORS preflight without auth.
			public.Method("OPTIONS", "/*", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				w.WriteHeader(http.StatusNoContent)
			}))
		}

	})
	// Protected endpoints (API handlers)
	r.Group(func(protected chi.Router) {
		if config.AuthEnabled {
			protected.Use(authnMiddleware)
			if authzMiddleware != nil {
				protected.Use(authzMiddleware)
			}
		}

		// Register routes - generated by 'fabrica generate'
		RegisterGeneratedRoutes(protected)
	})

	initializeMetricsServer(config)

	// Create HTTP server
	addr := remoteConfig.HttpListen
	server := &http.Server{
		Addr:         addr,
		Handler:      r,
		ReadTimeout:  time.Duration(config.ReadTimeout) * time.Second,
		WriteTimeout: time.Duration(config.WriteTimeout) * time.Second,
		IdleTimeout:  time.Duration(config.IdleTimeout) * time.Second,
	}

	// Start server in goroutine
	go func() {
		logStartupConfiguration(config, addr)

		if err := server.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatalf("Server failed: %v", err)
		}
	}()

	// Wait for interrupt signal for graceful shutdown
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	log.Println("Server shutting down...")
	serviceStop()

	// Graceful shutdown with timeout
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	if err := server.Shutdown(ctx); err != nil {
		return fmt.Errorf("server forced to shutdown: %w", err)
	}

	log.Println("Server exited")
	return nil
}

// Health check handler
func healthHandler(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	if _, err := w.Write([]byte(`{"status":"healthy","service":"remote-console"}`)); err != nil {
		log.Printf("failed to write health response: %v", err)
	}
}

// registerResourcePrefixes is defined in routes_generated.go

var versionCmd = &cobra.Command{
	Use:   "version",
	Short: "Print the version number",
	Long:  `Print the version number of remote-console`,
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("remote-console v1.0.0")
	},
}
