// Code generated by Fabrica dev. DO NOT EDIT.
// Template: init/metrics_helpers.go.tmpl
// Generated: 2026-07-08T18:41:14Z
//
// SPDX-FileCopyrightText: Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

package main

func initializeMetricsServer(config *Config) {

}
