// Code generated by Fabrica. DO NOT EDIT.
// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains OpenAPI 3.0 specification generation for all resources.
// Generated from: pkg/codegen/templates/server/openapi.go.tmpl
//
// To modify OpenAPI spec:
//  1. Edit the template file: pkg/codegen/templates/server/openapi.go.tmpl
//  2. Run 'fabrica generate' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// OpenAPI endpoints:
//   - GET /openapi.json - Returns OpenAPI 3.0 spec
//   - GET /docs - Returns Swagger UI
//
// This file automatically generates OpenAPI schemas from Go types using
// kin-openapi's openapi3gen package. No docstring annotations required.
package main

import (
	"encoding/json"
	"net/http"

	"github.com/OpenCHAMI/remote-console/apis/remote-console.openchami.io/v1"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/getkin/kin-openapi/openapi3gen"
)

// ServeOpenAPISpec returns the OpenAPI 3.0 specification
func ServeOpenAPISpec(w http.ResponseWriter, r *http.Request) {
	spec := GenerateOpenAPISpec()
	w.Header().Set("Content-Type", "application/json")
	if err := json.NewEncoder(w).Encode(spec); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

// ServeSwaggerUI returns the Swagger UI HTML page
func ServeSwaggerUI(w http.ResponseWriter, r *http.Request) {
	html := `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>remote_console API Documentation</title>
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/swagger-ui-dist@5.9.0/swagger-ui.css">
    <style>
        html { box-sizing: border-box; overflow: -moz-scrollbars-vertical; overflow-y: scroll; }
        *, *:before, *:after { box-sizing: inherit; }
        body { margin:0; padding:0; }
    </style>
</head>
<body>
    <div id="swagger-ui"></div>
    <script src="https://unpkg.com/swagger-ui-dist@5.9.0/swagger-ui-bundle.js"></script>
    <script src="https://unpkg.com/swagger-ui-dist@5.9.0/swagger-ui-standalone-preset.js"></script>
    <script>
        window.onload = function() {
            window.ui = SwaggerUIBundle({
                url: "/openapi.json",
                dom_id: '#swagger-ui',
                deepLinking: true,
                presets: [
                    SwaggerUIBundle.presets.apis,
                    SwaggerUIStandalonePreset
                ],
                plugins: [
                    SwaggerUIBundle.plugins.DownloadUrl
                ],
                layout: "StandaloneLayout"
            });
        };
    </script>
</body>
</html>`
	w.Header().Set("Content-Type", "text/html")
	w.Write([]byte(html))
}

// GenerateOpenAPISpec generates the complete OpenAPI 3.0 specification
func GenerateOpenAPISpec() *openapi3.T {
	spec := &openapi3.T{
		OpenAPI: "3.0.0",
		Info: &openapi3.Info{
			Title:       "remote_console API",
			Description: "Fabrica-generated REST API with Kubernetes-style resource management",
			Version:     "1.0.0",
			Contact: &openapi3.Contact{
				Name: "Fabrica Project",
				URL:  "https://github.com/openchami/fabrica",
			},
		},
		Servers: openapi3.Servers{
			{
				URL:         "http://localhost:8080",
				Description: "Development server",
			},
		},
		Paths: openapi3.NewPaths(),
		Components: &openapi3.Components{
			Schemas: make(openapi3.Schemas),
		},
	}

	// Register all resource paths
	registerConsolePaths(spec)

	// Register /health endpoint
	healthOp := openapi3.NewOperation()
	healthOp.OperationID = "health"
	healthOp.Summary = "Service health"
	healthOp.Description = "Returns service health information"
	healthOp.Tags = []string{"Service"}
	healthResponseSchema := openapi3.NewObjectSchema().
		WithProperty("status", openapi3.NewStringSchema()).
		WithProperty("service", openapi3.NewStringSchema()).
		WithProperty("version", openapi3.NewStringSchema()).
		WithProperty("time", openapi3.NewStringSchema()).
		WithRequired([]string{"status"})
	healthExample := map[string]interface{}{
		"status":  "ok",
		"service": "remote_console",
		"version": "1.0.0",
		"time":    "2026-01-01T00:00:00Z",
	}
	healthResponseSchema.Example = healthExample
	healthOp.Responses = openapi3.NewResponses()
	healthOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Healthy").
			WithContent(map[string]*openapi3.MediaType{
				"application/json": {
					Schema:  &openapi3.SchemaRef{Value: healthResponseSchema},
					Example: healthExample,
				},
			}),
	})
	spec.Paths.Set("/health", &openapi3.PathItem{Get: healthOp})

	// Register /openapi.json endpoint (self-referential spec endpoint)
	openAPIJSONExample := map[string]interface{}{
		"openapi": "3.0.0",
		"info": map[string]interface{}{
			"title":   "remote_console API",
			"version": "1.0.0",
		},
	}
	openAPIJsonOp := openapi3.NewOperation()
	openAPIJsonOp.OperationID = "getOpenAPISpec"
	openAPIJsonOp.Summary = "Get OpenAPI specification"
	openAPIJsonOp.Description = "Returns the complete OpenAPI 3.0 specification for this API"
	openAPIJsonOp.Tags = []string{"Service"}
	openAPIJsonOp.Responses = openapi3.NewResponses()
	openAPIJsonOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("OpenAPI specification").
			WithContent(map[string]*openapi3.MediaType{
				"application/json": {
					Schema:  &openapi3.SchemaRef{Value: openapi3.NewObjectSchema()},
					Example: openAPIJSONExample,
				},
			}),
	})
	spec.Paths.Set("/openapi.json", &openapi3.PathItem{Get: openAPIJsonOp})

	// Register /docs endpoint (Swagger UI)
	docsOp := openapi3.NewOperation()
	docsOp.OperationID = "getSwaggerUI"
	docsOp.Summary = "API documentation UI"
	docsOp.Description = "Returns an interactive Swagger UI for exploring the API"
	docsOp.Tags = []string{"Service"}
	docsOp.Responses = openapi3.NewResponses()
	docsOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Swagger UI HTML page").
			WithContent(map[string]*openapi3.MediaType{
				"text/html": {
					Schema: &openapi3.SchemaRef{Value: openapi3.NewStringSchema()},
				},
			}),
	})
	spec.Paths.Set("/docs", &openapi3.PathItem{Get: docsOp})

	// Register custom (non-Fabrica-generated) paths.
	// Defined in openapi_extensions.go – safe to edit, never overwritten.
	registerCustomOpenAPIPaths(spec)

	return spec
}

// registerConsolePaths registers OpenAPI paths for Console resources
func registerConsolePaths(spec *openapi3.T) {
	// Generate schemas from Go types - NO ANNOTATIONS NEEDED
	resourceSchema, _ := openapi3gen.NewSchemaRefForValue(&v1.Console{}, spec.Components.Schemas)
	spec.Components.Schemas["Console"] = resourceSchema

	// Error response schema
	if _, exists := spec.Components.Schemas["ErrorResponse"]; !exists {
		errorSchema := openapi3.NewObjectSchema().
			WithProperty("error", openapi3.NewStringSchema()).
			WithRequired([]string{"error"})
		spec.Components.Schemas["ErrorResponse"] = &openapi3.SchemaRef{Value: errorSchema}
	}
	// List Consoles operation
	listOp := openapi3.NewOperation()
	listOp.OperationID = "listConsoles"
	listOp.Summary = "List all Console resources"
	listOp.Description = "Returns a list of all Console resources in the inventory"
	listOp.Tags = []string{"Console"}
	listOp.Responses = openapi3.NewResponses()
	arraySchema := openapi3.NewArraySchema()
	arraySchema.Items = &openapi3.SchemaRef{Ref: "#/components/schemas/Console"}
	listOp.Responses.Set("200", &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Successful response").
			WithJSONSchemaRef(&openapi3.SchemaRef{Value: arraySchema}),
	})
	listOp.Responses.Set("500", errorResponse())

	// Create path items
	collectionPath := &openapi3.PathItem{
		Get: listOp,
	}

	// Add paths to spec
	spec.Paths.Set("/remote-console/consoles", collectionPath)
}

func patchRequestBody() *openapi3.RequestBodyRef {
	patchSchema := &openapi3.SchemaRef{Value: openapi3.NewObjectSchema()}
	return &openapi3.RequestBodyRef{
		Value: &openapi3.RequestBody{
			Required: true,
			Content: openapi3.Content{
				"application/merge-patch+json": &openapi3.MediaType{Schema: patchSchema},
				"application/json-patch+json":  &openapi3.MediaType{Schema: patchSchema},
				"application/shorthand-patch":  &openapi3.MediaType{Schema: patchSchema},
				"application/json":             &openapi3.MediaType{Schema: patchSchema},
			},
		},
	}
}

// Helper function for error responses
func errorResponse() *openapi3.ResponseRef {
	return &openapi3.ResponseRef{
		Value: openapi3.NewResponse().
			WithDescription("Error response").
			WithJSONSchemaRef(&openapi3.SchemaRef{
				Ref: "#/components/schemas/ErrorResponse",
			}),
	}
}
